# .air.toml
root = "."
tmp_dir = "/tmp"

[build]
cmd = "go build -buildvcs=false -o /tmp/main ./cmd/server"
bin = "/tmp/main"
include_ext = ["go", "tpl", "tmpl", "json", "yaml"]
exclude_dir = ["ui", "postgres_data", "tmp", "bin"]

[log]
time = true
