version: "3.9"

services:
  opsie-db-dev:
    image: postgres:15
    container_name: opsie-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/bin
    ports:
      - "3905:3905"
    command: air
    depends_on:
      - opsie-db-dev
    env_file:
      - .env

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    environment:
      - VITE_APP_VERSION=v-dev
      - VITE_APP_ENV=development
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev

volumes:
  postgres_data:
