FROM golang:1.25.1-alpine
RUN apk add --no-cache git curl bash
RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 3905
CMD ["air", "-c", ".air.toml"] 
