name: Build Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci

      - name: Build UI
        working-directory: ./ui
        run: npm run build

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install Go dependencies
        run: go mod download

      - name: Build server binary
        run: go build -v ./cmd/server/main.go


